# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from models import create_user_profile

class TestCreateUser(unittest.TestCase):

    def test_create_user_profile(self):
        user = User.objects.create_user('test_user', 'test@example.com', 'test_password')
        user_profile = UserDetail.objects.get(user=user)
        self.assertEqual(user_profile.user, user)

    def test_create_user_profile_with_existing_user(self):
        user = User.objects.create_user('test_user', 'test@example.com', 'test_password')
        user_profile = UserDetail.objects.get(user=user)
        self.assertEqual(user_profile.user, user)
        try:
            create_user_profile(sender=User, instance=user, created=True)
        except Exception as e:
            self.assertTrue(isinstance(e, IntegrityError))

if __name__ == '__main__':
    unittest.main()
