# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import get

class TestGet(unittest.TestCase):

    def test_get_success(self):
        request = HttpRequest()
        response = get(request)
        self.assertEqual(response.status_code, 200)

    def test_get_failure(self):
        request = HttpRequest()
        response = get(request)
        self.assertEqual(response.status_code, 404)

if __name__ == '__main__':
    unittest.main()
