# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

from .views import Get_object

class TestGetObject(TestCase):

    def test_Get_object_dcb1ac47bd(self):
        request_user = Get_object().get_object()
        self.assertEqual(request_user.username, 'self.request.user.username')

    def test_Get_object_dcb1ac47bd_fail(self):
        request_user = Get_object().get_object()
        self.assertNotEqual(request_user.username, 'self.request.user.username')

