# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse_lazy
from .views import PasswordsChangeView


class PasswordsChangeViewTest(TestCase):

    def setUp(self):
        self.user = User.objects.create_user(username='testuser', password='12345678')
        self.client.login(username='testuser', password='12345678')

    def test_Form_valid_cd84ba476e(self):
        form_data = {
            'old_password': '12345678',
            'new_password1': 'new_password',
            'new_password2': 'new_password',
        }
        response = self.client.post(reverse_lazy('passwords_change'), data=form_data)
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse_lazy('passwords_change_done'))

    def test_Form_invalid_cd84ba476e(self):
        form_data = {
            'old_password': 'wrong_password',
            'new_password1': 'new_password',
            'new_password2': 'new_password',
        }
        response = self.client.post(reverse_lazy('passwords_change'), data=form_data)
        self.assertEqual(response.status_code, 200)
        self.assertFormError(response, 'form', 'old_password', 'Incorrect password.')

