# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from models import save_user_profile

class TestSaveUserProfile(unittest.TestCase):

    def test_Save_user_profile_1ba43a1a05(self):
        # Test case to check if the save_user_profile() method is called when a new user is created.
        user = User.objects.create_user(username='test_user', password='test_password')
        self.assertTrue(save_user_profile.called)

    def test_Save_user_profile_1ba43a1a06(self):
        # Test case to check if the save_user_profile() method is called when a user is updated.
        user = User.objects.create_user(username='test_user', password='test_password')
        user.username = 'updated_test_user'
        user.save()
        self.assertTrue(save_user_profile.called)

    def test_Save_user_profile_1ba43a1a07(self):
        # Test case to check if the save_user_profile() method is not called when a user is deleted.
        user = User.objects.create_user(username='test_user', password='test_password')
        user.delete()
        self.assertFalse(save_user_profile.called)

    def test_Save_user_profile_1ba43a1a08(self):
        # Test case to check if the save_user_profile() method raises an exception when the userdetail object does not exist.
        user = User.objects.create_user(username='test_user', password='test_password')
        userdetail = user.userdetail
        userdetail.delete()
        with self.assertRaises(Exception):
            save_user_profile(sender, instance)

