# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from .models import UserDetail
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class TestCreateUser(unittest.TestCase):

    def test_create_user_profile(self):
        user = User.objects.create_user('test_user', 'test@example.com', 'test_password')
        self.assertTrue(UserDetail.objects.filter(user=user).exists())

    def test_create_user_profile_with_existing_user(self):
        user = User.objects.create_user('test_user', 'test@example.com', 'test_password')
        UserDetail.objects.create(user=user)
        self.assertRaises(IntegrityError, UserDetail.objects.create, user=user)

