# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse

from views import logoutView

class LogoutViewTest(TestCase):

    def setUp(self):
        self.user = get_user_model().objects.create_user(username='testuser', password='12345')
        self.client.login(username='testuser', password='12345')

    def test_logoutView_success(self):
        response = self.client.get(reverse('user:logout'))
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response.url, reverse('user:login'))
        self.assertTrue(response.wsgi_request.user.is_authenticated is False)

    def test_logoutView_failure(self):
        self.client.logout()
        response = self.client.get(reverse('user:logout'))
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response.url, reverse('user:login'))
        self.assertTrue(response.wsgi_request.user.is_authenticated is False)

