# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from django.contrib.auth import get_user_model
from django.urls import reverse

class TestGet(unittest.TestCase):

    def setUp(self):
        self.user = get_user_model().objects.create_user(username='testuser', password='12345')
        self.client.login(username='testuser', password='12345')

    def test_get_success(self):
        response = self.client.get(reverse('get'))
        self.assertEqual(response.status_code, 200)

    def test_get_failure(self):
        self.client.logout()
        response = self.client.get(reverse('get'))
        self.assertEqual(response.status_code, 302)

