# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

from django.test import TestCase
from django.urls import reverse
from views import registerView

class RegisterViewTest(TestCase):

    def test_registerView_success(self):
        data = {
            'first_name': 'John',
            'last_name': 'Doe',
            'username': 'johndoe',
            'email': 'johndoe@example.com',
            'password': 'password',
            'repassword': 'password',
        }
        response = self.client.post(reverse('user:register'), data=data)
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('user:login'))

    def test_registerView_failure(self):
        data = {
            'first_name': 'John',
            'last_name': 'Doe',
            'username': 'johndoe',
            'email': 'johndoe@example.com',
            'password': 'password',
            'repassword': 'wrongpassword',
        }
        response = self.client.post(reverse('user:register'), data=data)
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('user:register'))

