# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import get_object

class TestGetObject(unittest.TestCase):

    def test_get_object_success(self):
        request_user = get_object(self)
        self.assertEqual(request_user.username, 'test_user')

    def test_get_object_failure(self):
        with self.assertRaises(Http404):
            get_object(self, username='non_existing_user')

if __name__ == '__main__':
    unittest.main()
