# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from .models import MyModel

class Test__str__(unittest.TestCase):

    def test___str___57494adc14(self):
        """
        Test that the __str__ method returns the expected string.
        """
        my_model = MyModel()
        # TODO: Change the value of my_model.name to a valid value
        my_model.name = "John Smith"
        self.assertEqual(str(my_model), "John Smith")

    def test___str___57494adc14_2(self):
        """
        Test that the __str__ method returns the expected string when the name is None.
        """
        my_model = MyModel()
        # TODO: Change the value of my_model.name to None
        my_model.name = None
        self.assertEqual(str(my_model), "")

