# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from .models import UserProfile

class TestSaveUserProfile(unittest.TestCase):

    def test_Save_user_profile_1ba43a1a05(self):
        user = User.objects.create_user(username='testuser', password='12345')
        user_profile = UserProfile.objects.create(user=user, first_name='John', last_name='Doe')
        user_profile.save()
        self.assertTrue(user_profile.userdetail.pk)

    def test_Save_user_profile_with_no_userdetail_1ba43a1a05(self):
        user = User.objects.create_user(username='testuser', password='12345')
        user_profile = UserProfile.objects.create(user=user, first_name='John', last_name='Doe')
        with self.assertRaises(Exception):
            user_profile.save()

