# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.test import TestCase, Client
from django.urls import reverse

class LogoutViewTest(TestCase):

    def setUp(self):
        self.client = Client()
        self.user = User.objects.create_user(username='testuser', password='12345')
        self.client.login(username='testuser', password='12345')

    def test_logoutView_success(self):
        response = self.client.get(reverse('user:logout'))
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('user:login'))
        self.assertEqual(response.cookies['sessionid'].value, '')

    def test_logoutView_failure(self):
        self.client.logout()
        response = self.client.get(reverse('user:logout'))
        self.assertEqual(response.status_code, 302)
        self.assertRedirects(response, reverse('user:login'))
        self.assertEqual(response.cookies['sessionid'].value, '')

