# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from django.contrib.auth import authenticate, login, logout
from django.contrib.messages import get_messages
from django.urls import reverse
from views import loginView

class LoginViewTest(TestCase):

    def test_LoginView_675a2b3a6b(self):
        # Test successful login
        response = self.client.post(reverse('user:login'), {'username': 'testuser', 'password': 'secret'})
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response.url, reverse('pages:index'))
        messages = get_messages(response.wsgi_request)
        self.assertEqual(len(messages), 1)
        self.assertEqual(messages[0].level, messages.SUCCESS)
        self.assertEqual(messages[0].message, 'Login successful! Welcome, testuser')

    def test_LoginView_675a2b3a6c(self):
        # Test failed login
        response = self.client.post(reverse('user:login'), {'username': 'testuser', 'password': 'wrongpassword'})
        self.assertEqual(response.status_code, 302)
        self.assertEqual(response.url, reverse('user:login'))
        messages = get_messages(response.wsgi_request)
        self.assertEqual(len(messages), 1)
        self.assertEqual(messages[0].level, messages.ERROR)
        self.assertEqual(messages[0].message, 'Check your information and try again!')

