# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import get_object

class TestGetObject(unittest.TestCase):

    def test_get_object_success(self):
        # Create a user
        user = User.objects.create_user(username='testuser', password='12345')

        # Create a post
        post = Post.objects.create(title='Test Post', body='Test Body', author=user)

        # Get the post
        get_object(self, queryset=Post.objects.all(), pk=post.pk)

    def test_get_object_failure(self):
        # Create a user
        user = User.objects.create_user(username='testuser', password='12345')

        # Create a post
        post = Post.objects.create(title='Test Post', body='Test Body', author=user)

        # Try to get the post with a different user
        with self.assertRaises(Http404):
            get_object(self, queryset=Post.objects.all(), pk=post.pk, user=User.objects.create_user(username='anotheruser', password='12345'))

    def test_get_object_not_found(self):
        # Try to get a post that doesn't exist
        with self.assertRaises(Http404):
            get_object(self, queryset=Post.objects.all(), pk=10000)

