# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from models import Tag


class TestTagStr(unittest.TestCase):

    def test___str___57494adc14(self):
        tag = Tag(name='Test Tag')
        self.assertEqual(str(tag), 'Test Tag')

    def test___str___with_empty_name(self):
        tag = Tag(name='')
        self.assertEqual(str(tag), '')

    def test___str___with_none_name(self):
        tag = Tag(name=None)
        self.assertEqual(str(tag), '')

    def test___str___with_ip_address(self):
        tag = Tag(ip='192.168.1.1')
        self.assertEqual(str(tag), '192.168.1.1')

    def test___str___with_title(self):
        tag = Tag(title='Test Tag')
        self.assertEqual(str(tag), 'Test Tag')

    def test___str___with_multiple_fields(self):
        tag = Tag(name='Test Tag', ip='192.168.1.1', title='Test Tag')
        self.assertEqual(str(tag), 'Test Tag')

