# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from .models import Tag


class TestTagStr(unittest.TestCase):

    def test___str___57494adc14(self):
        tag = Tag(name='Test Tag')
        self.assertEqual(str(tag), 'Test Tag')

    def test___str___with_no_name(self):
        tag = Tag()
        self.assertEqual(str(tag), '')

    def test___str___with_hit_count(self):
        tag = Tag(name='Test Tag')
        tag.hit_count = 1
        self.assertEqual(str(tag), 'Test Tag (1)')

    def test___str___with_ip(self):
        tag = Tag(ip='127.0.0.1')
        self.assertEqual(str(tag), '127.0.0.1')

    def test___str___with_title(self):
        tag = Tag(title='Test Tag')
        self.assertEqual(str(tag), 'Test Tag')

    def test___str___with_all_fields(self):
        tag = Tag(name='Test Tag', ip='127.0.0.1', title='Test Tag')
        self.assertEqual(str(tag), 'Test Tag (127.0.0.1) - Test Tag')

