# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from .views import PostDetailView

class TestGet(unittest.TestCase):

    def test_Get_77d719334e(self):
        request = HttpRequest()
        post = Post.objects.create(title='Test Post', body='Test Body')
        response = PostDetailView.as_view()(request, pk=post.pk)
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, post.title)
        self.assertContains(response, post.body)

    def test_Get_404(self):
        request = HttpRequest()
        response = PostDetailView.as_view()(request, pk=9999)
        self.assertEqual(response.status_code, 404)

