# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from .views import PostDetailView

class TestGetContextData(unittest.TestCase):

    def test_Get_context_data_bb289b6072(self):
        # Success case
        request = HttpRequest()
        post = Post.objects.create(title='Test Post', slug='test-post', body='Test Post Body', available=True, category_id=1)
        view = PostDetailView()
        view.object = post
        context = view.get_context_data(object=post)
        self.assertEqual(context['popularposts'].count(), 3)
        self.assertEqual(context['relatedposts'].count(), 3)
        self.assertEqual(context['categories'].count(), Category.objects.all().count())
        self.assertEqual(context['tags'].count(), Tag.objects.all().count())
        self.assertEqual(context['comments'].count(), 10)

    def test_Get_context_data_with_no_posts(self):
        # Failure case
        request = HttpRequest()
        view = PostDetailView()
        view.object = None
        context = view.get_context_data(object=None)
        self.assertEqual(context['popularposts'].count(), 0)
        self.assertEqual(context['relatedposts'].count(), 0)
        self.assertEqual(context['categories'].count(), Category.objects.all().count())
        self.assertEqual(context['tags'].count(), Tag.objects.all().count())
        self.assertEqual(context['comments'].count(), 0)

