# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from .views import search

class SearchTest(TestCase):

    def test_search_success(self):
        response = self.client.get('/search/?query=test')
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Search Results')

    def test_search_no_results(self):
        response = self.client.get('/search/?query=nonexistent')
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'No results found')

