# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.template.defaultfilters import slugify
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post, Category, Tag, HitCount, Comment
from .views import PostDeleteView

class TestPostDeleteView(unittest.TestCase):

    def test_delete_success(self):
        post = Post.objects.create(
            title="Test Post",
            slug="test-post",
            body="Test post body",
            author=self.user,
            category=self.category,
            tag=self.tag,
        )
        response = self.client.post(
            reverse("blog:post_delete", kwargs={"pk": post.pk}), follow=True
        )
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Post successfully deleted.")

    def test_delete_fail(self):
        post = Post.objects.create(
            title="Test Post",
            slug="test-post",
            body="Test post body",
            author=self.user,
            category=self.category,
            tag=self.tag,
        )
        response = self.client.get(
            reverse("blog:post_delete", kwargs={"pk": post.pk}), follow=True
        )
        self.assertEqual(response.status_code, 404)
        self.assertContains(response, "Page not found")

