# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from .views import PostList


class TestPostList(TestCase):

    def test_PostList_with_category_slug(self):
        category_slug = 'test-category'
        response = self.client.get(reverse('posts', kwargs={'category_slug': category_slug}))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Posts By Category')

    def test_PostList_with_tag_slug(self):
        tag_slug = 'test-tag'
        response = self.client.get(reverse('posts', kwargs={'tag_slug': tag_slug}))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Posts By Tag')

    def test_PostList_with_no_slug(self):
        response = self.client.get(reverse('posts'))
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'All Posts')

    def test_PostList_with_invalid_slug(self):
        category_slug = 'invalid-category'
        response = self.client.get(reverse('posts', kwargs={'category_slug': category_slug}))
        self.assertEqual(response.status_code, 404)

        tag_slug = 'invalid-tag'
        response = self.client.get(reverse('posts', kwargs={'tag_slug': tag_slug}))
        self.assertEqual(response.status_code, 404)

