# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from views import get_client_ip

class TestGetClientIp(unittest.TestCase):

    def test_get_client_ip_with_x_forwarded_for(self):
        request = MockRequest(META={'HTTP_X_FORWARDED_FOR': '127.0.0.1'})
        ip = get_client_ip(request)
        self.assertEqual(ip, '127.0.0.1')

    def test_get_client_ip_without_x_forwarded_for(self):
        request = MockRequest(META={'REMOTE_ADDR': '127.0.0.1'})
        ip = get_client_ip(request)
        self.assertEqual(ip, '127.0.0.1')

