# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from .views import PostCreateView, PostUpdateView, PostDeleteView

class TestGetSuccessUrl(unittest.TestCase):

    def test_get_success_url_success(self):
        post = Post.objects.create(
            category_id=1,
            title='Test Post',
            slug='test-post',
            content='Test content'
        )
        view = PostCreateView()
        view.object = post
        self.assertEqual(view.get_success_url(), '/posts/category/test-category/1/test-post/')

    def test_get_success_url_failure(self):
        view = PostCreateView()
        view.object = None
        with self.assertRaises(Http404):
            view.get_success_url()

    def test_get_success_url_update_success(self):
        post = Post.objects.create(
            category_id=1,
            title='Test Post',
            slug='test-post',
            content='Test content'
        )
        view = PostUpdateView()
        view.object = post
        self.assertEqual(view.get_success_url(), '/posts/category/test-category/1/test-post/')

    def test_get_success_url_update_failure(self):
        view = PostUpdateView()
        view.object = None
        with self.assertRaises(Http404):
            view.get_success_url()

    def test_get_success_url_delete_success(self):
        post = Post.objects.create(
            category_id=1,
            title='Test Post',
            slug='test-post',
            content='Test content'
        )
        view = PostDeleteView()
        view.object = post
        self.assertEqual(view.get_success_url(), '/user/profile/')

    def test_get_success_url_delete_failure(self):
        view = PostDeleteView()
        view.object = None
        with self.assertRaises(Http404):
            view.get_success_url()

