# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from django.test import TestCase
from views import search

class SearchTest(TestCase):

    def test_Search_b57a59566d(self):
        # Test search with existing query
        response = self.client.get('/search/?query=test')
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'Search Results')

        # Test search with non-existing query
        response = self.client.get('/search/?query=non-existing')
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'No results found')

        # Test search with empty query
        response = self.client.get('/search/?query=')
        self.assertEqual(response.status_code, 200)
        self.assertContains(response, 'No results found')

if __name__ == '__main__':
    unittest.main()
