# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import PostList

class TestPostList(unittest.TestCase):

    def test_PostList_892bcb0c98(self):
        # Test case to check if the PostList view returns a 200 status code
        response = self.client.get('/posts/')
        self.assertEqual(response.status_code, 200)

    def test_PostList_with_category(self):
        # Test case to check if the PostList view returns a 200 status code when a category is specified
        response = self.client.get('/posts/category/test-category/')
        self.assertEqual(response.status_code, 200)

    def test_PostList_with_tag(self):
        # Test case to check if the PostList view returns a 200 status code when a tag is specified
        response = self.client.get('/posts/tag/test-tag/')
        self.assertEqual(response.status_code, 200)

    def test_PostList_with_invalid_category(self):
        # Test case to check if the PostList view returns a 404 status code when an invalid category is specified
        response = self.client.get('/posts/category/invalid-category/')
        self.assertEqual(response.status_code, 404)

    def test_PostList_with_invalid_tag(self):
        # Test case to check if the PostList view returns a 404 status code when an invalid tag is specified
        response = self.client.get('/posts/tag/invalid-tag/')
        self.assertEqual(response.status_code, 404)

