# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import dispatch

class TestDispatch(unittest.TestCase):

    def test_Dispatch_e87ceff3c8_success(self):
        request = 'request'
        args = 'args'
        kwargs = 'kwargs'
        post = 'post'
        self.assertEqual(dispatch(request, args, kwargs), post)

    def test_Dispatch_e87ceff3c8_failure(self):
        request = 'request'
        args = 'args'
        kwargs = 'kwargs'
        post = 'post'
        with self.assertRaises(Http404):
            dispatch(request, args, kwargs)

if __name__ == '__main__':
    unittest.main()
