# Test generated by RoostGPT for test python-django using AI Type Vertex AI and AI Model code-bison-32k

import unittest
from views import delete

class TestDelete(unittest.TestCase):

    def test_delete_success(self):
        request = HttpRequest()
        response = delete(request)
        self.assertEqual(response.status_code, 200)

    def test_delete_failure(self):
        request = HttpRequest()
        response = delete(request)
        self.assertEqual(response.status_code, 404)

